---
- hosts: eos
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli

  vars_files:
    - secure/initial_password.yml

  handlers:
    - name: save configuration
      become: true
      arista.eos.eos_command:
        commands: write

  tasks:
    - name: Ensure eAPI via HTTPS is enabled. Ensure access via HTTP is disabled.
      become: true
      arista.eos.eos_eapi:
        enable_http: false
        enable_https: true
      notify:
        - save configuration
