---
interfaces:
  - name: "Et1"
    description: "spine-1"
    ips:
      - "10.253.0.3/31"
    enabled: true
  - name: "Et2"
    description: "spine-2"
    ips:
      - "10.253.32.3/31"
    enabled: true
  - name: "Eth3"
    description: server-1
    ips:
      - "10.242.1.2"
  - name: "Eth4"
    description: server-2
    ips:
      - "10.242.129.2"
  - name: "Eth5"
    description: server-3
    ips:
      - "10.242.2.2"
  - name: "Eth6"
    description: server-4
    ips:
      - "10.242.130.2"